### ISSUE TITLE
Joining an in-progress game breaks scoreboard names

### ISSUE THREAD

**Issue by matekdev** [TTTReborn/ttt-reborn#265]
## Prerequisites

- [X] I have searched [existing bug reports](https://github.com/TTTReborn/ttt-reborn/issues?q=label%3Aissue%2Fbug-report) and confirmed my issue is not already reported.

## Summary

When you join a game that is in progress with other players, their player names do not showcase on the scoreboard.

## Expected behavior

We should see the player names on the scoreboard whenever you join a game that is in progress.

**Comment by mzegar** [comment]
The problem is that the `Scoreboard` UI element is created BEFORE `Client.All` is populated with data.
